---
apiVersion: v1
data:
  password: dGhpc0lzSnVzdEFuRXhhbXBsZTIwMTkh
kind: Secret
metadata:
  name: mysql-pass
  labels:
    app: "wordpress-F9EBEE89-BD33-414B-85FE-4348A3949B75"
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless-svc
  labels:
    app: wordpress-F9EBEE89-BD33-414B-85FE-4348A3949B75
spec:
  ports:
    - port: 3306
  selector:
    app: "wordpress-F9EBEE89-BD33-414B-85FE-4348A3949B75"
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: wordpress-F9EBEE89-BD33-414B-85FE-4348A3949B75
spec:
  selector:
    matchLabels:
      app: wordpress-F9EBEE89-BD33-414B-85FE-4348A3949B75

  replicas: 1
  serviceName: mysql-headless-svc
  template:
    metadata:
      labels:
        app: wordpress-F9EBEE89-BD33-414B-85FE-4348A3949B75
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      storageClassName: standard
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
