---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  labels:
    app: wordpress-F9EBEE89-BD33-414B-85FE-4348A3949B75
spec:
  ports:
    - port: 80
  selector:
    app: wordpress-F9EBEE89-BD33-414B-85FE-4348A3949B75
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-nodeport
  labels:
    app: wordpress-F9EBEE89-BD33-414B-85FE-4348A3949B75
spec:
  ports:
    - port: 80
  selector:
    app: wordpress-F9EBEE89-BD33-414B-85FE-4348A3949B75
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress-F9EBEE89-BD33-414B-85FE-4348A3949B75
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  #storageClassName: csi-rbd-sc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress-F9EBEE89-BD33-414B-85FE-4348A3949B75
spec:
  selector:
    matchLabels:
      app: wordpress-F9EBEE89-BD33-414B-85FE-4348A3949B75
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-F9EBEE89-BD33-414B-85FE-4348A3949B75
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-headless-svc
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
